services:
  - type: web
    name: gpt-chat-library
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm --prefix server install && npm run build
    startCommand: concurrently -k "node server/server.js" "npm run preview"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_ENABLED
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        sync: false
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: VITE_HF_TOKEN
        sync: false
